'use strict';
/* ============ Solde et mises ============ */
let shownBal=S.balance,balAnim;
function renderBal(){const el=$('#bal-v');const from=shownBal,to=S.balance,t0=performance.now();cancelAnimationFrame(balAnim);const st=t=>{const k=Math.min(1,(t-t0)/550),e=1-Math.pow(1-k,3);shownBal=from+(to-from)*e;el.textContent=fmt(k<1?Math.round(shownBal):to);if(k<1)balAnim=requestAnimationFrame(st);else shownBal=to};balAnim=requestAnimationFrame(st);const p=$('#bal');p.classList.remove('up','down');void p.offsetWidth;if(to>from+.001)p.classList.add('up');else if(to<from-.001)p.classList.add('down');document.dispatchEvent(new Event('bal'))}
function limitOk(a){const L=S.lim;if(L.time>0&&(Date.now()-sess.start)/60000>=L.time){modalMsg('Limite de temps atteinte',`Ta session dure depuis plus de ${L.time} min, la limite que tu as fixée. Fais une pause, ou modifie la limite dans <a href="#/rg" class="gold">Jeu responsable</a>.`);return false}if(L.wager>0&&sess.wag+a>L.wager+1e-9){modalMsg('Limite de mises atteinte',`Cette mise ferait dépasser ta limite de session de ${fmt(L.wager)} ◈ (déjà misé : ${fmt(sess.wag)} ◈). Tu peux la modifier dans <a href="#/rg" class="gold">Jeu responsable</a>.`);return false}return true}
function canBet(a){a=r2(a);if(!(a>0)){toast('Choisis une mise supérieure à 0.','err');return false}if(a>S.balance+1e-9){lowBal(a);return false}return limitOk(a)}
function take(a){a=r2(a);S.balance=r2(S.balance-a);S.wagered=r2(S.wagered+a);sess.wag+=a;renderBal();save()}
function give(a){a=r2(a);if(a<=0)return;S.balance=r2(S.balance+a);S.won=r2(S.won+a);sess.won+=a;renderBal();save()}
function lowBal(a){if(S.refill!==today()&&S.balance<1000){const m=modal(`<div style="font-size:44px">🪙</div><h3 class="mt">Solde insuffisant</h3><p class="mp">Il te manque ${fmt(a-S.balance)} ◈ pour cette mise. Récupère ta recharge gratuite du jour : 5 000 ◈.</p><button class="btn btn-gold btn-big" id="rf">Recevoir 5 000 ◈</button><button class="btn btn-ghost btn-big" style="margin-top:8px" data-close>Plus tard</button>`);$('#rf',m.el).onclick=()=>{S.refill=today();give(5000);S.won=r2(S.won-5000);save();snd('coin');confetti(60,true);m.close()}}else toast(`Solde insuffisant : baisse ta mise ou passe par <a href="#/promo" class="gold">Promotions</a>.`,'err')}
